version: '3'
services:
  db:
    image: mysql:5.7.29
    container_name: test_mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
       # for now set explicit, but then get from env
       MYSQL_DATABASE: 'test_db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'test_password'
